version: "3.9"

services:
  nginx:
    container_name: ca-l9-nginx
    image: nginx:1.23.2
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    container_name: ca-l9-php
    # image: php:8.1.11-fpm-alpine3.16
    build: ./docker/php/
    working_dir: /var/www
    env_file:
      - ./docker/mysql/.env
    volumes:
      - ./src:/var/www
    # tty: true
    ports:
      - "5173:5173" # vitejs dev server
    depends_on:
      - mysql

  mysql:
    container_name: ca-l9-mysql
    image: mysql:8.0.31
    env_file:
        - ./docker/mysql/.env
    volumes:
        - ./docker/mysql/data:/var/lib/mysql
    ports:
        - "33066:3306"